import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

Z = np.genfromtxt("datos1.dat")
X, Y = np.meshgrid(np.linspace(0,1,100), np.linspace(0,1,100))
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa condicion inicial")
plt.savefig("Caso1(t = 0s)")

Z1 = np.genfromtxt("datos2.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z1)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 1000s")
plt.savefig("Caso1(t = 1000s)")

Z2 = np.genfromtxt("datos3.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z2)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 2500s")
plt.savefig("Caso1(t = 2500s)")

Z3 = np.genfromtxt("datos4.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z3)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 1000s")
plt.savefig("Caso2(t = 1000s)")

Z4 = np.genfromtxt("datos5.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z4)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 2500s")
plt.savefig("Caso2(t = 2500s)")

Z5 = np.genfromtxt("datos6.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z5)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 1000s")
plt.savefig("Caso3(t = 1000s)")

Z6 = np.genfromtxt("datos7.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z6)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 2500s")
plt.savefig("Caso3(t = 2500s)")


Z7 = np.genfromtxt("datos8.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z7)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 0s")
plt.savefig("Caso4(t = 0s)")

Z8 = np.genfromtxt("datos9.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z8)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 1000s")
plt.savefig("Caso4(t = 1000s)")

Z9 = np.genfromtxt("datos10.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z9)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 2500s")
plt.savefig("Caso4(t = 2500s)")