import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

Z = np.genfromtxt("datos1.dat")
X, Y = np.meshgrid(np.linspace(0,1,100), np.linspace(0,1,100))
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z)
ax.set_zlim(30, 120)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa condicion inicial")
plt.savefig("Caso1(t = 0s)")

Z1 = np.genfromtxt("datos2.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z1)
ax.set_zlim(30, 120)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 100s")
plt.savefig("Caso1(t = 100s)")

Z2 = np.genfromtxt("datos3.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z2)
ax.set_zlim(30, 120)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 2500s")
plt.savefig("Caso1(t = 2500s)")

Z3 = np.genfromtxt("datos4.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z3)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 100s")
plt.savefig("Caso2(t = 100s)")

Z4 = np.genfromtxt("datos5.dat")
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(X, Y, Z4)
ax.set_zlabel("Temperatura (C)")
ax.set_xlabel("X (m)")
ax.set_ylabel("Y (m)")
plt.title("Placa t = 2500s")
plt.savefig("Caso2(t = 2500s)")